In [44]:
# Ejercicio 01
import numpy as np

# Array 7x8 lleno de ceros de tipo entero
array1 = np.zeros((6, 7), dtype=int)

# Array 7x8 lleno de ceros salvo la primera fila que serán todo unos
array2 = np.zeros((6, 7), dtype=int)
for i in range(7):
    array2[0,i] = 1

# Array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8
array3 = np.zeros((6, 7), dtype=int)
for z in range(7):
    x = np.random.randint(5,8)
    array3[5,z] = x

# Mostrar los Arrays
print(array1,"\n")
print(array2,"\n")
print(array3,"\n")

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

[[1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [6 7 6 6 6 6 5]] 



In [45]:
# Ejercicio 02

# Vector de 10 elementos, siendo los impares 1 y los pares 2
vector = np.array([1 if i % 2 else 2 for i in range(10)])

# Tablero de ajedrez» 8x8, con 1 en las casillas negras y 0 en las casillas blancas
tablero = np.zeros((7, 7), dtype=int)
tablero[1::2, ::2] = 1
tablero[::2, 1::2] = 1

# Imprimir tableros
print(v,"\n")
print(chess,"\n")

[2 1 2 1 2 1 2 1 2 1] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



In [48]:
# Ejercicio 03

# Matriz aleatoria 7x7
mat = np.random.rand(7, 7)
min_val = mat.min()
max_val = mat.max()

# Normalización entre 0 y 1
normalized = (mat - min_val) / (max_val - min_val)

print("\nMatriz aleatoria:\n", mat)
print("\nEl valor MIN de la matriz aleatoria es: ", min_val, "\nEl valor MAX de la matriz aleatoria es: ", max_val)
print("\nMatriz normalizada:\n", normalized)


Matriz aleatoria:
 [[0.02713896 0.14454124 0.26901385 0.8905184  0.27912284 0.76413198
  0.43722155]
 [0.35370275 0.85380173 0.27014143 0.19167516 0.75296948 0.8038303
  0.3590844 ]
 [0.93273212 0.72478437 0.89203586 0.82074415 0.56095857 0.75261252
  0.45127208]
 [0.56408378 0.29618453 0.87845724 0.54222771 0.64256383 0.39841114
  0.46712114]
 [0.82534745 0.39494877 0.6210657  0.50145347 0.36052064 0.29542137
  0.37374462]
 [0.50930155 0.11043768 0.16000991 0.38570603 0.65872509 0.6284707
  0.21152032]
 [0.00599756 0.48326852 0.01703038 0.06776913 0.10323166 0.41260604
  0.7489808 ]]

El valor MIN de la matriz aleatoria es:  0.005997555135759058 
El valor MAX de la matriz aleatoria es:  0.9327321218773695

Matriz normalizada:
 [[0.0228128  0.14949662 0.28380973 0.95444896 0.29471792 0.81807073
  0.46531554]
 [0.37519395 0.91482956 0.28502646 0.20035683 0.80602575 0.8609075
  0.38100105]
 [1.         0.7756124  0.95608639 0.87915852 0.59883491 0.80564057
  0.48047687]
 [0.60220719 0.3

In [57]:
# Ejercicio 04

# Matriz inicial con 1 y 9
mat = np.ones((5,5),dtype=int)
mat[1:4,1:4]=0
mat[2,2]=9
print("Matriz original: \n",mat)


# Invertir lo valores de 9 y 1 de la Matriz anterior
mat_swapped = mat.copy()
mat_swapped[mat == 1] = -1
mat_swapped[mat == 9] = 1
mat_swapped[mat_swapped == -1] = 9
print("\nMatriz Invertida: \n",mat_swapped)

Matriz original: 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Matriz Invertida: 
 [[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]


In [75]:
# Ejercicio 05

# Crear la matriz principal
mat = np.arange(1, 31).reshape(6, 5)

verde_vals = [2, 8, 14, 20]
rojo_vals = [4, 5, 24, 25, 29, 30]
azul_vals = [11, 12, 16, 17]

# Extraer Matrices de cada color
verde_mask = np.isin(mat,verde_vals)
rojo_mask = np.isin(mat,rojo_vals)
azul_mask = np.isin(mat,azul_vals)

verde = mat[verde_mask]
rojo = mat[rojo_mask]
azul = mat[azul_mask]

print("Matriz original:\n", mat)
print("\nSubmatriz VERDE:", verde)
print("\nSubmatriz ROJA:", rojo)
print("\nSubmatriz AZUL:", azul)

Matriz original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Submatriz VERDE: [ 2  8 14 20]

Submatriz ROJA: [ 4  5 24 25 29 30]

Submatriz AZUL: [11 12 16 17]


In [74]:
# Ejercicio 06

# Matriz verde
matriz_verde = np.array([
    [255,  34,  45,  16,  24,  99],
    [200,  50,  67,  15,  56,  88],
    [165,  67,  34,  26,  87,  70],
    [120, 100,  45,  56,  67,   0],
    [ 45, 225,  35,  67,  50,  44],
    [ 36, 255,  24,  78,  77,  23]
])

# Matriz celeste 
matriz_celeste = np.array([
    [  0,   0,   0],
    [  0, 255,   0],
    [  0,   0,   0]
])

# Funcion para el reemplazo
def reemplazar_por_celeste(matriz, valor, reemplazo):
    filas, columnas = matriz.shape
    for i in range(1, filas - 1):
        for j in range(1, columnas - 1):
            if matriz[i, j] == valor:
                matriz[i-1:i+2, j-1:j+2] = reemplazo
    return matriz

matriz_modificada = reemplazar_por_celeste(matriz_verde.copy(), 50, matriz_celeste)

print("Matriz original:")
print(matriz_verde)
print("\nMatriz modificada:")
print(matriz_modificada)

Matriz original:
[[255  34  45  16  24  99]
 [200  50  67  15  56  88]
 [165  67  34  26  87  70]
 [120 100  45  56  67   0]
 [ 45 225  35  67  50  44]
 [ 36 255  24  78  77  23]]

Matriz modificada:
[[  0   0   0  16  24  99]
 [  0 255   0  15  56  88]
 [  0   0   0  26  87  70]
 [120 100  45   0   0   0]
 [ 45 225  35   0 255   0]
 [ 36 255  24   0   0   0]]
