In [2]:
import numpy as np
# Matriz unidimensional
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [20]:
# Matriz bidimensional
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [24]:
array=np.array([[1, 2, 3, 4],[5, 6, 7, 8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
# Cantidad de memoria asignada
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [27]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


In [28]:
# Velocidad
import time
SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)

start = time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time() - start)*1000)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start2= time.time()
result2= A1+A2
print((time.time() - start2)*1000)

175.93026161193848
5.827903747558594


In [34]:
# Matrices vacías y con valores

# Crear una matriz de unos - 3 filas 4 columnas
unos = np.ones((3, 4))

# Crear una matriz de ceros - 3 filas 4 columnas
ceros = np.zeros((3, 4))

# Crear una matriz con valores aleatorios
aleatorios = np.random.rand(3, 4)

# Crear una matriz vacía
vacia = np.empty((3, 2))

# Crear una matriz con un solo valor
constante = np.full((2, 2), 8)

# Crear una matriz con valores espaciados uniformemente
espaciada = np.arange(0, 30, 5)
espaciada2 = np.linspace(0, 2, 5)

# Crear una matriz identidad
identidad = np.eye(4, 4)
identidad2 = np.identity(4)

print("Unos:\n", unos)
print("Ceros:\n", ceros)
print("Aleatorios:\n", aleatorios)
print("Vacia:\n", vacia)
print("Un solo valor:\n", constante)
print("Espaciada:\n", espaciada)
print("Espaciada 2:\n", espaciada2)
print("Identidad:\n", identidad)
print("Identidad 2:\n", identidad2)

Unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Aleatorios:
 [[0.22130082 0.37278089 0.49673564 0.82747938]
 [0.1676529  0.10460733 0.41807674 0.70399782]
 [0.84693817 0.53474387 0.14849689 0.05755506]]
Vacia:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]
Un solo valor:
 [[8 8]
 [8 8]]
Espaciada:
 [ 0  5 10 15 20 25]
Espaciada 2:
 [0.  0.5 1.  1.5 2. ]
Identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Identidad 2:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
# Inspeccionar las matrices de Numpy
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz: \n",mat)
# Conocer las dimensiones de una matriz
print("Dimensiones:", mat.ndim)

# Conocer el tipo de los datos
print("Tipo de datos:", mat.dtype)

# Conocer el tamaño y forma de la matriz
print("Tamaño total:", mat.size)
print("Forma:", mat.shape)

# Cambio de forma de una matriz
a = np.array([[8, 9, 10],[11, 12, 13]])
print("Matriz base:")
print(a)
ref = a.reshape((3, 2))
print("Reformada:")
print(ref)

Matriz: 
 [[1 2 3]
 [4 5 6]]
Dimensiones: 2
Tipo de datos: int64
Tamaño total: 6
Forma: (2, 3)
Matriz base:
[[ 8  9 10]
 [11 12 13]]
Reformada:
[[ 8  9]
 [10 11]
 [12 13]]


In [42]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Matriz: \n",mat)
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
print("Elemento fila 0 col 2:", mat[0, 2])

# Extraer los valores de todas las filas ubicados en la columna 3
print("Columna 3 completa:", mat[0:, 2])

Matriz: 
 [[1 2 3 4]
 [5 6 7 8]]
Elemento fila 0 col 2: 3
Columna 3 completa: [3 7]


In [3]:
# Operaciones Matemáticas entre matrices de NumPy

# Encontrar el mínimo, máximo y la suma
mat = np.array([2,45,800])
print("Mínimo:", mat.min())
print("Máximo:", mat.max())
print("Suma:", mat.sum())
a = np.array([[1,4,81],[33, 44, 50]])
# Calcular la raíz cuadrada y la desviación estándar
print("Raíz cuadrada:\n", np.sqrt(a))
print("Desviación estándar:\n", np.std(a))

Mínimo: 2
Máximo: 800
Suma: 847
Raíz cuadrada:
 [[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
Desviación estándar:
 27.5121185419565


In [5]:
# Calcular la suma, resta, multiplicación y división de dos matrices
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[1, 2, 3], [3, 4, 5]])
print("Suma:\n", a + b)
print("Resta:\n", a - b)
print("Multiplicación:\n", a * b)
print("División:\n", a / b)

Suma:
 [[ 2  4  6]
 [ 6  8 10]]
Resta:
 [[0 0 0]
 [0 0 0]]
Multiplicación:
 [[ 1  4  9]
 [ 9 16 25]]
División:
 [[1. 1. 1.]
 [1. 1. 1.]]
